### ISSUE TITLE
Create new Iconclass component to match new data model

### ISSUE THREAD

**Issue by EeveesEyes** [hochschule-darmstadt-UAS/ddk-artbrowser#11]
**Reason (Why?)**
Iconclasses describe the content of artworks. The Iconclass-entity should have its own page in the artbrowser and each class should be visit-able by the user.

**Solution (What?)**
[iconclass.org](iconclass.org) provides an [api](iconclass.org/help/lod) which shall be used to fetch the description data for each class. The dataset consists of parent- and sub-classes, keywords and the textual description of the class. Because the user has no idea what the iconclass-identifier means, the related classes have to be fetched, too, to display their title in the hierarchy (see mockup). This means, each page-load sends 1 + parent classes (max. 6) + sub classes (max. 10) requests to the iconclass api. It is also possible to get several icon classes with one API-Call using several notations (e. g. `http://iconclass.org/json/?notation=25FF& ... &notation=51A`). 
The sub-class request can be delayed until 'subclasses v' is clicked.

Mockup:
![image](https://user-images.githubusercontent.com/28682931/99882521-5a921c80-2c21-11eb-96b8-261e3d58c067.png)

The sample image shall be filled with a random artwork, assigned to the class. This functionality could be realized with a query like [this](https://github.com/hochschule-darmstadt-UAS/ddk-artbrowser/blob/64b29989871a75fb0c9fcd9800e1d383114faeb7/app/src/app/core/services/elasticsearch/data.service.ts#L166).

The Keywords are indexed by iconclass.org and therefor searchable, but no user-interaction is required in the userinterface - so they can be plain text. In future, there could be an option to search by iconclass-keyword (each [iconclass-query](http://iconclass.org/rkd/0/?q=lion&q_s=1&fmt=json) results in a set of iconclasses).

The Artwork-Carousel shall be filled with related artworks, obviously.

**Out of scope**
For the first release, these features are out of scope:
- make keywords search-able
- a sample image is displayed at the top
- an iconclass overview page (like artists, ..) (because it should not be a simple listing)

**Relation to other Issues**
This is a good issue to start, because issue #4 doesn't have to be ready to implement this. 

**Acceptance criteria**
- all german attributes provided by the iconclass api are shown in the ui
- data is fetched from the iconclass api

**Comment by EeveesEyes** [comment]
@BernhardHumm what do you think about this proposal?

**Comment by BernhardHumm** [comment]
I like this feature a lot and, in fact, my ideas were quire similar.
The image on top does not need to be random but could simply be the one with the highest ranking (Prio B)
