### ISSUE TITLE
Parse "Entity" from lido-file

### ISSUE THREAD

**Issue by MadelineWall** [hochschule-darmstadt-UAS/ddk-artbrowser#31]
**Reason (Why?)**
Will be filled later !

**Solution (What?)**
Will be filled later !

**Out of scope**
Entity has attributes named "id, label, type, count, rank, icon, sourceID" with no prio, an attribute named "altLables" with prio 2 and attributes named "image, imageSmall, imageMedium, altLabels" with prio 3. These attributes will not be filled at the moment

**Relation to other Issues**
#21 

**Acceptance criteria**

**Comment by EeveesEyes** [comment]
The Entity class is an abstract class, there is no need to parse this. We should probably rename it to `AbstractEntity`
