### ISSUE TITLE
Set up elasticsearch staging server

### ISSUE THREAD

**Issue by EeveesEyes** [hochschule-darmstadt-UAS/ddk-artbrowser#4]
**Reason (Why?)**
We need a dedicated staging backend for the development.

**Solution (What?)**
Therefor an elasticsearch server needs to be set up on the staging server and (for now) loaded with the data samples.
In addition the elasticsearch endpoints `_search` and `_count` shall be exposed so that they are reachable from the frontend application.

**Acceptance criteria**
The frontend can query the sample data from the staging elasticsearch server.

**Comment by mauamy** [comment]
Done for week, so this can be closed.
