### ISSUE TITLE
Investigate Ranking of data

### ISSUE THREAD

**Issue by EeveesEyes** [hochschule-darmstadt-UAS/ddk-artbrowser#40]
**Reason (Why?)**
Currently the rating of data sets is based on the number of attributes / foreign keys, but the ddk data sets seem not to be as diverse in that regard.

**Solution (What?)**
Develop a metric, which describes the 'importance' of an entity. 

**Relation to other Issues**
The search suggestions are currently based on the ranking (#39)

**Acceptance criteria**
A proposal is made what metric can be used to rank data sets

**Comment by BernhardHumm** [comment]
Implement the ranking of artworks as in openartbrowser.org .

Only investigate other alternatives if problems with the existing approach are apparent.

 

 

 

 

Von: Adrian Kailus <notifications@github.com> 
Gesendet: Donnerstag, 10. Dezember 2020 13:49
An: hochschule-darmstadt-UAS/ddk-artbrowser <ddk-artbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt-UAS/ddk-artbrowser] Investigate Ranking of data (#40)

 

Reason (Why?)
Currently the rating of data sets is based on the number of attributes / foreign keys, but the ddk data sets seem not to be as diverse in that regard.

Solution (What?)
Develop a metric, which describes the 'importance' of an entity.

Relation to other Issues
The search suggestions are currently based on the ranking (#39 <https://github.com/hochschule-darmstadt-UAS/ddk-artbrowser/issues/39> )

Acceptance criteria
A proposal is made what metric can be used to rank data sets

**Comment by mauamy** [comment]
I investigated a bit into the artwork count distribution and came up with these results:
![ddk-artwork-counts-all-files](https://user-images.githubusercontent.com/28662686/104818320-2b65e900-5827-11eb-9a05-853fc3563e74.png)

(Given that the code which generates the count is correct) we have an extremely small diversity of count values which probably leads to a bad search result entity type distribution.

**Comment by BernhardHumm** [comment]
I don’t understand the axes of this diagram.

 

 

------------------------------------

 

Von: Yannick Mau <notifications@github.com> 
Gesendet: Samstag, 16. Januar 2021 18:21
An: hochschule-darmstadt-UAS/ddk-artbrowser <ddk-artbrowser@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Comment <comment@noreply.github.com>
Betreff: Re: [hochschule-darmstadt-UAS/ddk-artbrowser] Investigate Ranking of data (#40)

 

I investigated a bit into the artwork count distribution and came up with these results:
 <https://user-images.githubusercontent.com/28662686/104818320-2b65e900-5827-11eb-9a05-853fc3563e74.png> 

(Given that the code which generates the count is correct) we have an extremely small diversity of count values which probably leads to a bad search result entity type distribution.

**Comment by EeveesEyes** [comment]
As I understand it, there are about 410k documents with a count less than 20 and a few with much higher counts. This gives a rank (aka relative rank) of about 0.22 for most documents, so our ranking is not as diverse as it could be if the count were to conform to a normal distribution. 
I see a quick fix: apply a log normalization function rather than a linear one. This would result in a more diverse "bottom end" of the ranking.

**Comment by EeveesEyes** [comment]
Nevertheless, my fix does not work for documents with the exact same number. So we need to base our ranking on something else. Maybe we could somehow add the "importance" of related entities to the rank? An artwork by an artist who has painted more pictures would then rank higher than an artwork with the same number of attributes, but an artist who has painted fewer pictures.

**Comment by BernhardHumm** [comment]
We should discuss the current ranking implementation in detail. I’m sure we’ll find a good solution.

 

 

------------------------------------

Von: Adrian Kailus <notifications@github.com> 
Gesendet: Montag, 18. Januar 2021 14:15
An: hochschule-darmstadt-UAS/ddk-artbrowser <ddk-artbrowser@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Comment <comment@noreply.github.com>
Betreff: Re: [hochschule-darmstadt-UAS/ddk-artbrowser] Investigate Ranking of data (#40)

 

Nevertheless, my fix does not work for documents with the exact same number. So we need to base our ranking on something else. Maybe we could somehow add the "importance" of related entities to the rank? An artwork by an artist who has painted more pictures would then rank higher than an artwork with the same number of attributes, but an artist who has painted fewer pictures.

**Comment by EeveesEyes** [comment]
The ranking in OpenArtBrowser is described here: https://github.com/hochschule-darmstadt/openartbrowser/wiki/System-architecture#data-enhancement-ranking-and-merging-intermediate-json-files
