### ISSUE TITLE
Modify Artwork component to match new data model

### ISSUE THREAD

**Issue by EeveesEyes** [hochschule-darmstadt-UAS/ddk-artbrowser#5]
**Reason (Why?)**
A site for the presentation of the artworks. 

**Solution (What?)**
All informations (name, measurements, recordLegal, resources, inscriptions, types, genres, location, artists, iconographies, materials) should be displayed on this page and a picture of the artwork. Other pictures of the artwork is also shown.

Second draft:
![image](https://user-images.githubusercontent.com/28682931/100519714-101d1c80-319a-11eb-8b3e-8f7e430feffc.png)

To be discussed:
- display of image rights (an example is shown in the screenshot)
- cooperation link with ddk

**Out of scope**
For the first release, these features are out of scope:
- alternative name
- inscriptions

**Relation to other Issues**
 All Entity-Pages: Artwork: #5 Artist: #6 Material: #7 Genre: #8 Location: #9 Type: #10 Iconclass: #11

**Acceptance criteria**

**Comment by BernhardHumm** [comment]
looks really good to me.
legal information is OK
Cooperation link with DDK not necessary right now (according to Email by K. Bulle). However, mentioning data source in legal notice is mandatory.

**Comment by KaiDrie** [comment]
Maybe rights information could be put to the left or right of the picture, written upwards/sideways?

**Comment by EeveesEyes** [comment]
We thought of this, but it intervenes with the background being as plain and neutral as possible. The idea is, that the image is the only thing in reading-direction the user sees. That's why we don't have the colored background from the start page, too.
Maybe we could put the rights information in the right column of the artists/location/inception part? One argument against putting it to the right side of the image list is, that the list grows, which takes the space needed for the rights information.

**Comment by MaiThiD** [comment]
Is this position an option?

![image](https://user-images.githubusercontent.com/64202398/101548690-93b1e700-39ac-11eb-87a8-dca2444f46e9.png)
