### ISSUE TITLE
ETL: Implement Count and Ranking

### ISSUE THREAD

**Issue by mauamy** [hochschule-darmstadt-UAS/ddk-artbrowser#50]
**Reason (Why?)**
All entities need to have a `count` and a `rank`.

**Solution (What?)**
After the import step, the field `count` and `rank` must be set correctly for each entity object. How `count` and `rank` are calculated is described in the [related wiki section](https://github.com/hochschule-darmstadt-UAS/ddk-artbrowser/wiki/System-architecture#ranking)

**Acceptance criteria**
All entity object that are created by the xml importer have a valid `count` and `rank` field.

**Comment by BernhardHumm** [comment]
Maybe you can reuse most of the counting/ranking code in openArtBrowser.

 

 

 

Von: Yannick Mau <notifications@github.com> 
Gesendet: Donnerstag, 17. Dezember 2020 13:00
An: hochschule-darmstadt-UAS/ddk-artbrowser <ddk-artbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt-UAS/ddk-artbrowser] ETL: Implement Count and Ranking (#50)

 

Reason (Why?)
All entities need to have a count and a rank.

Solution (What?)
After the import step, the field count and rank must be set correctly for each entity object. How count and rank are calculated is described in the related wiki section <https://github.com/hochschule-darmstadt-UAS/ddk-artbrowser/wiki/System-architecture#ranking> 

Acceptance criteria
All entity object that are created by the xml importer have a valid count and rank field.

**Comment by mauamy** [comment]
Implemented in #3

**Comment by mauamy** [comment]
Implemented in #3
