### ISSUE TITLE
Error message for wrong ids and error page for 404

### ISSUE THREAD

**Issue by EeveesEyes** [hochschule-darmstadt-UAS/ddk-artbrowser#66]
**Reason (Why?)**
Currently there is no feedback on the website when a missing id is requested.

**Solution (What?)**
Implement a 404 / missing content page or other feedback to the user.

**Acceptance criteria**
The user is not simply redirected to start and gets a proper feedback.

**Comment by BernhardHumm** [comment]
How can this happen?

 

 

-- 

 

Von: Adrian Kailus <notifications@github.com> 
Gesendet: Donnerstag, 14. Januar 2021 12:51
An: hochschule-darmstadt-UAS/ddk-artbrowser <ddk-artbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt-UAS/ddk-artbrowser] Error pages for wrong ids (#66)

 

Reason (Why?)
Currently there is no feedback on the website when a missing id is requested.

Solution (What?)
Implement a 404 / missing content page or other feedback to the user.

Acceptance criteria
The user is not simply redirected to start and gets a proper feedback.

**Comment by EeveesEyes** [comment]
The user can simply enter a wrong url.
